title: Nodeal
description: Full doc

lang: en
icon: ðŸ”§

repo_theme_light: default
repo_theme_dark: dark
repo_trophies:
  enabled: true
  theme_light: flat
  theme_dark: gitdimmed

markdown: kramdown

search: true
